drop table if exists hits;

create table if not exists hits (
id bigint generated by default as identity not null,
app varchar not null,
uri varchar not null,
ip varchar not null,
timestamp timestamp without time zone
);